<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>import AdminShell from '../../components/AdminShell.vue';import StatusBadge from '../../components/StatusBadge.vue';import {inspections} from '../../api/mock';</script>
<template><AdminShell><template #title>检验任务</template>
  <section class="page-heading compact"><div><p>INSPECTION OPERATIONS</p><h1>检验任务中心</h1><span>统一管理 IQC、IPQC、FQC 与委外检验批次。</span></div><button class="solid">＋ 创建检验任务</button></section>
  <section class="summary-strip"><div><span>今日计划</span><b>24</b><small>已完成 18</small></div><div><span>待检验</span><b>18</b><small>加急 3 批</small></div><div><span>检验中</span><b>6</b><small>平均用时 26 分钟</small></div><div><span>今日不合格</span><b class="red">2</b><small>已创建 NCR</small></div><div class="completion"><header><span>当日完成率</span><b>75%</b></header><div><i></i></div><small>目标完成率 ≥ 95%</small></div></section>
  <section class="card data-card"><header class="table-toolbar"><div class="segmented"><button class="active">全部任务 <b>42</b></button><button>待检验 <b>18</b></button><button>检验中 <b>6</b></button><button>已完成 <b>18</b></button></div><div><label>⌕ <input placeholder="搜索批次或物料"/></label><button>筛选</button><button>导出</button></div></header>
    <table><thead><tr><th><input type="checkbox"/></th><th>检验批次</th><th>类型</th><th>物料信息</th><th>来源 / 供应商</th><th>批量 / 抽样</th><th>计划时间</th><th>检验员</th><th>状态 / 结果</th><th></th></tr></thead><tbody><tr v-for="i in inspections" :key="i.no"><td><input type="checkbox"/></td><td><b>{{i.no}}</b><small>{{i.source}}</small></td><td><span class="outline-tag">{{i.type}}</span></td><td><b>{{i.material}}</b><small>{{i.code}}</small></td><td><b>{{i.supplier}}</b><small>{{i.source}}</small></td><td><b>{{i.batch}}</b><small>抽样 {{i.sample}}</small></td><td><b>{{i.date}}</b><small v-if="i.priority==='加急'" class="urgent-text">优先处理</small></td><td><span class="person">{{i.owner.slice(0,1)}}</span>{{i.owner}}</td><td><StatusBadge :value="i.result||i.status"/></td><td><button class="more">•••</button></td></tr></tbody></table>
    <footer class="pager"><span>共 42 条记录，每页 10 条</span><div><button>‹</button><button class="current">1</button><button>2</button><button>3</button><button>4</button><button>›</button></div></footer>
  </section>
</AdminShell></template>
