<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>import AdminShell from '../../components/AdminShell.vue';import StatusBadge from '../../components/StatusBadge.vue';import {risks,capa} from '../../api/mock';</script>
<template><AdminShell><template #title>不合格与 CAPA</template>
  <section class="page-heading compact"><div><p>NONCONFORMANCE & CAPA</p><h1>质量问题闭环中心</h1><span>从问题登记、评审处置到纠正预防措施与效果验证。</span></div><div><button class="soft">8D 报告模板</button><button class="solid">＋ 登记不合格</button></div></section>
  <section class="process-strip"><div v-for="(p,i) in [['01','问题登记','7'],['02','评审处置','4'],['03','原因分析','3'],['04','措施执行','5'],['05','效果验证','2'],['06','关闭归档','28']]" :key="p[0]"><small>{{p[0]}}</small><span>{{p[1]}}</span><b>{{p[2]}}</b><i v-if="i<5">›</i></div></section>
  <section class="nc-layout"><article class="card"><header class="card-title"><div><h2>进行中的不合格事项</h2><p>按严重度、截止时间排序</p></div><button>全部来源 ⌄</button></header><div class="nc-cards"><div v-for="r in risks" :key="r.no"><header><StatusBadge :value="r.level"/><b>{{r.no}}</b><em :class="{'late':r.due.includes('逾期')}">{{r.due}}</em></header><h3>{{r.title}}</h3><p>{{r.detail}}</p><footer><span>负责人 <b>{{r.owner}}</b></span><span>当前阶段 <b>{{r.level==='严重'?'效果验证':r.level==='重大'?'原因分析':'措施执行'}}</b></span><button>查看详情 →</button></footer></div></div></article>
    <article class="card capa-panel"><header class="card-title"><div><h2>CAPA 措施进度</h2><p>纠正与预防措施执行情况</p></div><button>查看全部</button></header><div class="capa-list"><div v-for="c in capa" :key="c.no"><header><div><b>{{c.title}}</b><small>{{c.no}} · 关联 {{c.nc}}</small></div><StatusBadge :value="c.status"/></header><div class="progress-head"><span>负责人 {{c.owner}} · 截止 {{c.due}}</span><b>{{c.progress}}%</b></div><div class="progress-line"><i :style="{width:c.progress+'%'}"></i></div></div></div><footer class="capa-summary"><div><span>按期完成率</span><b>92.6%</b></div><div><span>平均关闭周期</span><b>6.8 天</b></div></footer></article>
  </section>
</AdminShell></template>
