/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.qms;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import java.util.regex.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@SpringBootTest @AutoConfigureMockMvc class DeepQualityOpsTests{@Autowired MockMvc mvc;String token;/**
                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                     */
@BeforeEach void auth()throws Exception{String j=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\"admin\",\"password\":\"admin123\"}")).andReturn().getResponse().getContentAsString();var m=Pattern.compile("\\\"token\\\":\\\"([^\\\"]+)\\\"").matcher(j);Assertions.assertTrue(m.find());token=m.group(1);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void failedInspectionDrivesNcrAndCapaToClosure()throws Exception{long p=plan("PLAN-A",1);long i=id(call("/api/quality-ops/inspections","{\"inspectionNo\":\"IQC-A\",\"planId\":"+p+",\"lotQty\":1000,\"sampleQty\":50}").andReturn());long n=idAt(call("/api/quality-ops/inspections/"+i+"/result","{\"defectQty\":3,\"severity\":\"MAJOR\",\"description\":\"尺寸超差\"}").andExpect(jsonPath("$.data.inspection.result").value("FAILED")).andReturn(),2);call("/api/quality-ops/nonconformances/"+n+"/disposition","{\"disposition\":\"CAPA_REQUIRED\"}");long c=id(call("/api/quality-ops/capas","{\"capaNo\":\"CAPA-A\",\"ncId\":"+n+",\"rootCause\":\"治具磨损\",\"correctiveAction\":\"更换治具并全检\",\"preventiveAction\":\"增加寿命点检\"}").andReturn());call("/api/quality-ops/capas/"+c+"/submit","{\"evidenceHash\":\"abcdef0123456789abcdef\"}");admin("/api/admin/quality-ops/capas/"+c+"/verify","{\"effective\":true,\"note\":\"复验通过\"}").andExpect(jsonPath("$.data.status").value("CLOSED"));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void passingInspectionCreatesNoNcr()throws Exception{long p=plan("PLAN-B",2);long i=id(call("/api/quality-ops/inspections","{\"inspectionNo\":\"IQC-B\",\"planId\":"+p+",\"lotQty\":500,\"sampleQty\":30}").andReturn());call("/api/quality-ops/inspections/"+i+"/result","{\"defectQty\":1,\"severity\":\"MINOR\",\"description\":\"轻微外观\"}").andExpect(jsonPath("$.data.inspection.result").value("PASSED")).andExpect(jsonPath("$.data.nonconformance").doesNotExist());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void criticalNonconformanceCannotUseAsIs()throws Exception{long p=plan("PLAN-C",0);long i=id(call("/api/quality-ops/inspections","{\"inspectionNo\":\"IQC-C\",\"planId\":"+p+",\"lotQty\":100,\"sampleQty\":10}").andReturn());long n=idAt(call("/api/quality-ops/inspections/"+i+"/result","{\"defectQty\":1,\"severity\":\"CRITICAL\",\"description\":\"安全缺陷\"}").andReturn(),2);call("/api/quality-ops/nonconformances/"+n+"/disposition","{\"disposition\":\"USE_AS_IS\"}").andExpect(status().isConflict());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 long plan(String n,int ac)throws Exception{long id=id(admin("/api/admin/quality-ops/plans","{\"planNo\":\""+n+"\",\"materialCode\":\"MAT-001\",\"supplierCode\":\"SUP-001\",\"aql\":1.0,\"acceptanceNumber\":"+ac+"}").andReturn());admin("/api/admin/quality-ops/plans/"+id+"/activate","{}");return id;}/**
                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                            */
ResultActions call(String u,String b)throws Exception{return mvc.perform(post(u).header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content(b));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
ResultActions admin(String u,String b)throws Exception{return call(u,b);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
long id(MvcResult r)throws Exception{return idAt(r,1);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
long idAt(MvcResult r,int ordinal)throws Exception{var m=Pattern.compile("\"id\":(\\d+)").matcher(r.getResponse().getContentAsString());for(int x=0;x<ordinal;x++)Assertions.assertTrue(m.find(),r.getResponse().getContentAsString());return Long.parseLong(m.group(1));}}
