/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.qms.deep;import jakarta.persistence.*;import org.springframework.http.*;import org.springframework.stereotype.*;import org.springframework.transaction.annotation.*;import org.springframework.web.server.*;import java.time.*;import java.util.*;
@Service @Transactional(readOnly=true) public class DeepQualityService{private final EntityManager em;public DeepQualityService(EntityManager e){em=e;}
 @Transactional public PlanView createPlan(PlanInput x){if(x.aql()<=0||x.acceptanceNumber()<0)throw bad("AQL与接收数配置无效");var p=new QualityPlan(x.planNo(),x.materialCode(),x.supplierCode(),x.aql(),x.acceptanceNumber());em.persist(p);audit("CREATE_PLAN",p.planNo,x.materialCode());return view(p);}@Transactional public PlanView activatePlan(Long id){var p=plan(id);if(!"DRAFT".equals(p.status))throw conflict("检验方案状态不可启用");p.status="ACTIVE";return view(p);}
 @Transactional public InspectionView inspect(InspectionInput x){var p=plan(x.planId());if(!"ACTIVE".equals(p.status))throw conflict("检验方案未启用");if(x.lotQty()<1||x.sampleQty()<1||x.sampleQty()>x.lotQty())throw bad("批量与抽样量无效");var i=new InspectionOrder(x.inspectionNo(),p.id,x.lotQty(),x.sampleQty());em.persist(i);return view(i);}@Transactional public InspectionResult record(Long id,ResultInput x){var i=inspection(id);if(!"CREATED".equals(i.status))throw conflict("检验单已完成");if(x.defectQty()<0||x.defectQty()>i.sampleQty)throw bad("不良数超出抽样范围");var p=plan(i.planId);i.defectQty=x.defectQty();i.result=x.defectQty()<=p.acceptanceNumber?"PASSED":"FAILED";i.status="COMPLETED";i.completedAt=LocalDateTime.now();NcView nc=null;if("FAILED".equals(i.result)){var n=new QualityNonconformance("NC-"+i.inspectionNo,i.id,x.severity(),x.description());em.persist(n);nc=view(n);}audit("COMPLETE_INSPECTION",i.inspectionNo,i.result);return new InspectionResult(view(i),nc);}
 @Transactional public NcView disposition(Long id,DispositionInput x){var n=nc(id);if(!"OPEN".equals(n.status))throw conflict("不合格品状态不可处置");if("CRITICAL".equals(n.severity)&&"USE_AS_IS".equals(x.disposition()))throw conflict("严重不合格品禁止让步接收");if(!Set.of("REWORK","SCRAP","RETURN","USE_AS_IS","CAPA_REQUIRED").contains(x.disposition()))throw bad("处置方式无效");n.disposition=x.disposition();n.status="CAPA_REQUIRED".equals(x.disposition())||"CRITICAL".equals(n.severity)?"CAPA_REQUIRED":"DISPOSITIONED";return view(n);}
 @Transactional public CapaView capa(CapaInput x){var n=nc(x.ncId());if(!"CAPA_REQUIRED".equals(n.status))throw conflict("该不合格项不要求CAPA");var c=new QualityCapa(x.capaNo(),n.id,x.rootCause(),x.correctiveAction(),x.preventiveAction());em.persist(c);return view(c);}@Transactional public CapaView submitCapa(Long id,EvidenceInput x){var c=capa(id);if(!"OPEN".equals(c.status))throw conflict("CAPA状态不可提交");if(x.evidenceHash()==null||x.evidenceHash().length()<16)throw bad("整改证据摘要不足");c.evidenceHash=x.evidenceHash();c.status="READY_VERIFY";return view(c);}@Transactional public CapaView verifyCapa(Long id,VerifyInput x){var c=capa(id);if(!"READY_VERIFY".equals(c.status))throw conflict("CAPA尚未提交验证");if(!x.effective()){c.status="OPEN";c.evidenceHash=null;return view(c);}c.status="CLOSED";var n=nc(c.ncId);n.status="CLOSED";audit("VERIFY_CAPA",c.capaNo,x.note());return view(c);}
 public Workspace workspace(){return new Workspace(plans(),inspections(),ncs(),capas());}
 private QualityPlan plan(Long id){var x=em.find(QualityPlan.class,id);if(x==null)throw missing("检验方案不存在");return x;}private InspectionOrder inspection(Long id){var x=em.find(InspectionOrder.class,id);if(x==null)throw missing("检验单不存在");return x;}private QualityNonconformance nc(Long id){var x=em.find(QualityNonconformance.class,id);if(x==null)throw missing("不合格项不存在");return x;}private QualityCapa capa(Long id){var x=em.find(QualityCapa.class,id);if(x==null)throw missing("CAPA不存在");return x;}private void audit(String a,String n,String d){em.persist(new QualityAudit(a,n,d));}
 private List<PlanView>plans(){return em.createQuery("select p from QualityPlan p order by p.id desc",QualityPlan.class).getResultList().stream().map(this::view).toList();}private List<InspectionView>inspections(){return em.createQuery("select i from InspectionOrder i order by i.id desc",InspectionOrder.class).getResultList().stream().map(this::view).toList();}private List<NcView>ncs(){return em.createQuery("select n from QualityNonconformance n order by n.id desc",QualityNonconformance.class).getResultList().stream().map(this::view).toList();}private List<CapaView>capas(){return em.createQuery("select c from QualityCapa c order by c.id desc",QualityCapa.class).getResultList().stream().map(this::view).toList();}
 private PlanView view(QualityPlan p){return new PlanView(p.id,p.planNo,p.materialCode,p.supplierCode,p.aql,p.acceptanceNumber,p.status,p.lockVersion);}private InspectionView view(InspectionOrder i){return new InspectionView(i.id,i.inspectionNo,i.planId,i.lotQty,i.sampleQty,i.defectQty,i.result,i.status,i.completedAt,i.lockVersion);}private NcView view(QualityNonconformance n){return new NcView(n.id,n.ncNo,n.inspectionId,n.severity,n.description,n.disposition,n.status,n.lockVersion);}private CapaView view(QualityCapa c){return new CapaView(c.id,c.capaNo,c.ncId,c.rootCause,c.correctiveAction,c.preventiveAction,c.evidenceHash,c.status,c.lockVersion);}
 private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}private ResponseStatusException missing(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
 public record PlanInput(String planNo,String materialCode,String supplierCode,double aql,int acceptanceNumber){}public record InspectionInput(String inspectionNo,Long planId,int lotQty,int sampleQty){}public record ResultInput(int defectQty,String severity,String description){}public record DispositionInput(String disposition){}public record CapaInput(String capaNo,Long ncId,String rootCause,String correctiveAction,String preventiveAction){}public record EvidenceInput(String evidenceHash){}public record VerifyInput(boolean effective,String note){}public record PlanView(Long id,String planNo,String materialCode,String supplierCode,double aql,int acceptanceNumber,String status,long version){}public record InspectionView(Long id,String inspectionNo,Long planId,int lotQty,int sampleQty,int defectQty,String result,String status,LocalDateTime completedAt,long version){}public record InspectionResult(InspectionView inspection,NcView nonconformance){}public record NcView(Long id,String ncNo,Long inspectionId,String severity,String description,String disposition,String status,long version){}public record CapaView(Long id,String capaNo,Long ncId,String rootCause,String correctiveAction,String preventiveAction,String evidenceHash,String status,long version){}public record Workspace(List<PlanView>plans,List<InspectionView>inspections,List<NcView>nonconformances,List<CapaView>capas){}
}
