/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.qms.deep;import cn.zhuatech.qms.common.ApiResponse;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/admin/quality-ops") @PreAuthorize("hasRole('ADMIN')") public class DeepQualityAdminController{private final DeepQualityService s;/**
                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                        */
public DeepQualityAdminController(DeepQualityService x){s=x;}/**
                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                     */
@PostMapping("/plans")ApiResponse<?> plan(@RequestBody DeepQualityService.PlanInput x){return ApiResponse.ok(s.createPlan(x));}/**
                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                    */
@PostMapping("/plans/{id}/activate")ApiResponse<?> activate(@PathVariable Long id){return ApiResponse.ok(s.activatePlan(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@PostMapping("/capas/{id}/verify")ApiResponse<?> verify(@PathVariable Long id,@RequestBody DeepQualityService.VerifyInput x){return ApiResponse.ok(s.verifyCapa(id,x));}}
