/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.qms.deep;import cn.zhuatech.qms.common.ApiResponse;import org.springframework.web.bind.annotation.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/quality-ops") public class DeepQualityController{private final DeepQualityService s;/**
                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                           */
public DeepQualityController(DeepQualityService x){s=x;}/**
                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                   */
@GetMapping("/workspace")ApiResponse<?> workspace(){return ApiResponse.ok(s.workspace());}/**
                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                             */
@PostMapping("/inspections")ApiResponse<?> inspect(@RequestBody DeepQualityService.InspectionInput x){return ApiResponse.ok(s.inspect(x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                        */
@PostMapping("/inspections/{id}/result")ApiResponse<?> result(@PathVariable Long id,@RequestBody DeepQualityService.ResultInput x){return ApiResponse.ok(s.record(id,x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@PostMapping("/nonconformances/{id}/disposition")ApiResponse<?> disposition(@PathVariable Long id,@RequestBody DeepQualityService.DispositionInput x){return ApiResponse.ok(s.disposition(id,x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
@PostMapping("/capas")ApiResponse<?> capa(@RequestBody DeepQualityService.CapaInput x){return ApiResponse.ok(s.capa(x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@PostMapping("/capas/{id}/submit")ApiResponse<?> submit(@PathVariable Long id,@RequestBody DeepQualityService.EvidenceInput x){return ApiResponse.ok(s.submitCapa(id,x));}}
